spring:
  cloud:
    stream:
      bindings:
        input:
          destination: tasktopic
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest

logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
          stream: DEBUG
